#!/usr/bin/env python
import sys
import kmertools
import numpy as np
from optparse import OptionParser

parser = OptionParser()
parser.add_option("-k", type='int', help="Kmer size", default=31)
parser.add_option("-s", "--spectrum", type='str', help='File to store kmer spectrum png')
parser.add_option("-m", "--smax", type='int', default=300, help="Maximum frequency in spectrum plot")
parser.add_option("-o", "--output", type='str', help="Output file for kmers and counts")
parser.add_option("-c", "--compress", action='store_true', help="Store kmer output file in compressed format")
parser.add_option("-f", "--fingerprint", action='store_true', help="Store MinHash fingerprint")

(options, args) = parser.parse_args()

kset = kmertools.KmerSet(options.k)

for arg in args:
    print 'Kmerizing', arg
    kset.kmerizeFile(arg)

if options.fingerprint:
    kset.minHash()

if options.output:
    print 'Writing output to', options.output
    kset.save(options.output, options.compress)

if options.spectrum:
    kset.plotSpectrum(options.spectrum, options.smax)

